version: "3.8"
services:
  web:    
    image: node:16-alpine
    platform: linux/amd64
    container_name: web
    stdin_open: true # because of https://github.com/facebook/create-react-app/issues/8688
    working_dir: /app
    command: [ "sh", "-c", "yarn && chown -R node:node node_modules && yarn dev" ]
    #environment:
        #- npm_config_proxy=${NPM_PROXY}
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        source: node-modules
        target: /app/node_modules
    networks:
      - radix
    ports:
      - "3000:3000"

  proxy:
    image: nginxinc/nginx-unprivileged:1.23
    #platform: linux/arm64
    platform: linux/amd64
    container_name: proxy
    environment:
      - APIM_SUB_KEY=${APIM_SUB_KEY}
      - API_BASE_URL=${API_BASE_URL}
      - EPN_URI=${EPN_URI}
      - FLX_URI=${FLX_URI}
      - PROJECTS_URI=${PROJECTS_URI}
      - SCM_URI=${SCM_URI}
      - WOPREP_URI=${WOPREP_URI}
      - M5LCI_URI=${M5LCI_URI}
      - MSL_URI=${MSL_URI}
    volumes:
      - type: bind
        source: ./proxy/server.dev.conf
        target: /default.conf
      - type: bind
        source: ./proxy/run_nginx.sh
        target: /run_nginx.sh
    command: [ "/bin/bash", "-c", ". run_nginx.sh" ]
    networks:
      - radix
    ports:
      - "8080:8080"

  auth-state:
    image: redis:5
    platform: linux/amd64
    container_name: auth-state
    networks:
      - radix
    ports:
      - "6379:6379"

  auth:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.2.1
    container_name: auth
    environment:
      - OAUTH2_PROXY_PROVIDER=oidc
      - OAUTH2_PROXY_OIDC_ISSUER_URL=https://login.microsoftonline.com/3aa4a235-b6e2-48d5-9195-7fcf05b459b0/v2.0
      - OAUTH2_PROXY_CLIENT_ID=${OAUTH2_PROXY_CLIENT_ID}
      - OAUTH2_PROXY_CLIENT_SECRET=${OAUTH2_PROXY_CLIENT_SECRET}
      - OAUTH2_PROXY_COOKIE_SECRET=${OAUTH2_PROXY_COOKIE_SECRET}
      - OAUTH2_PROXY_SCOPE=openid profile email offline_access ${API_RESOURCE_ID}
      - OAUTH2_PROXY_REDIRECT_URL=http://localhost:8000/oauth2/callback
      - OAUTH2_PROXY_HTTP_ADDRESS=http://:8000
      - OAUTH2_PROXY_UPSTREAMS=http://proxy:8080
      - OAUTH2_PROXY_COOKIE_REFRESH=60m
      - OAUTH2_PROXY_REDIS_CONNECTION_URL=redis://auth-state:6379 # Where to store session info (the auth-state component)
      - OAUTH2_PROXY_SESSION_STORE_TYPE=redis # We're using Redis for storing session info instead of cookies (cookies would get too big for Edge and Safari)
      - OAUTH2_PROXY_COOKIE_SECURE=false # only for development
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_PASS_ACCESS_TOKEN=true
      - OAUTH2_PROXY_PASS_USER_HEADERS=false
      - OAUTH2_PROXY_PASS_HOST_HEADERS=false
      - OAUTH2_PROXY_SKIP_PROVIDER_BUTTON=true
    networks:
      - radix
    ports:
      - "8000:8000" # In prod, this is served on port 443
networks:
  radix:
    name: radix

volumes:
  node-modules:
    name: radix-web_node-modules